networks:
  encuestas:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:uWFgZtVOqlnXMuhahTK+zmJ1D9dMBtUW8ZvTckMfGxo=
      DB_CONNECTION: mysql
      DB_HOST: laravel-becas-mysql_db-1
      DB_PORT: 3306
      DB_DATABASE: encuestas
      DB_USERNAME: admin
      DB_PASSWORD: admin
    networks:
      - encuestas
